### ISSUE TITLE
error parsing repo with port number

### ISSUE THREAD

**Issue by jlgeering** [Mercateo/dwatch#21]
an image named "hub.myhost.com:4567/myimage:mytag" has name "hub.myhost.com" and tags [ 4567/myimage, mytag]

**Comment by jlgeering** [comment]
... should be name: "hub.myhost.com:4567/myimage" and tags [ mytag ]

**Comment by otbe** [comment]
You are absolutely right. Ive placed a PR with some fixes and additional tests. 
Cant test it right now, but I will setup a test environment this weekend.

**Comment by otbe** [comment]
Fixed in v1.0.0-alpha.7. Thanks for reporting!
