### ISSUE TITLE
Debian (Ubuntu): Menu: Application/About does not seem to work

### ISSUE THREAD

**Issue by uweschaefer** [Mercateo/dwatch#4]
After installing the .deb on a Ubuntu16, the "About" Entry in the Application Menu does not seem to work.
Everything else works fine at the first glance.

**Comment by uweschaefer** [comment]
Uh, forgot: the exact build was: 1.0.0-alpha.3-18

**Comment by otbe** [comment]
Thanks for reporting. It seems that "orderFrontStandardAboutPanel" is only present on OS X...
Will be addressed in v1.0.0-alpha.4 :)

**Comment by uweschaefer** [comment]
i'd volunteer for testing on ubuntu
